### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by lnsru** [blargony/RFFEAnalyzer#7]
Dear All, 

I would love to use your analyzer professionally, however legal team insists that your project needs some kind of license. Could you help me, please, with this and add license to your project?

Thanks,
Linas

**Comment by blargony** [comment]
Not sure how I forgot to add one originally!  It now has the MIT license, which is very permissive so hopefully acceptable for your legal team.   If you find any problems with the code I appreciate it if you file issues or send a PR but it is not necessary.
